spring.application.name=banking-service
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_service
spring.datasource.username=username
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
spring.jap.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.banking-service=DEBUG

server.port=8081

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

spring.jackson.time-zone=UTC

